### ISSUE TITLE
Crashes if no artist

### ISSUE THREAD

**Issue by Dan-Wood** [regisb/spotify-onthego#21] opened 2017-05-05 06:01 UTC
```
# spotify-playlist "Massive" /spotify/Music/Massive/
Downloading playlist 'Massive' (id=3HXm13Cik1lje31z1frW95) from owner 'msdathk'
++ Processing Ice Cube - Smoke Some Weed - edited version
    Downloading https://www.youtube.com/watch?v=3pIqwhtINqw to /tmp/Ice Cube - Smoke Some Weed (Official Original).m4a
++ Processing Ice Cube - Check Yo Self - Remix;
    Downloading https://www.youtube.com/watch?v=JH7bJkG7EEA to /tmp/Ice Cube - Check yo Self (Remix).m4a
++ Processing Swedish House Mafia - Greyhound
    Downloading https://www.youtube.com/watch?v=hBRKSIj2tMc to /tmp/Swedish House Mafia - Greyhound (Original Mix).webm
WARNING:eyed3.mp3:Unable to find a valid mp3 frame in '/spotify/Music/Massive/Swedish House Mafia - Greyhound.mp3'
Traceback (most recent call last):
  File "/spotify/venv/bin/spotify-playlist", line 11, in <module>
    load_entry_point('spotify-onthego==0.0.5', 'console_scripts', 'spotify-playlist')()
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/scripts/cli.py", line 42, in download_playlist
    youtube_downloader.audio(track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/youtube.py", line 45, in audio
    self.convert_or_copy(audio_file_path, track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/youtube.py", line 58, in convert_or_copy
    id3.tag(dst_path, track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/id3.py", line 9, in tag
    audiofile.tag.artist = track.artist
AttributeError: 'NoneType' object has no attribute 'artist'

```

**Comment by Dan-Wood** [comment] 2017-05-05 06:01
On re-run

```
# spotify-playlist "Massive" /spotify/Music/Massive/
Downloading playlist 'Massive' (id=3HXm13Cik1lje31z1frW95) from owner 'msdathk'
++ Skipping Ice Cube - Smoke Some Weed - edited version
++ Skipping Ice Cube - Check Yo Self - Remix;
++ Skipping Swedish House Mafia - Greyhound
++ Processing Ice Cube - You Can Do It - Feat. Mack 10 And Ms Toi
    Downloading https://www.youtube.com/watch?v=fiB653NYF6E to /tmp/08 - Ice Cube - You Can Do It (feat. Mack 10 & Ms. Toi).webm
++ Processing Dire Straits - Sultans Of Swing
    Downloading https://www.youtube.com/watch?v=8Pa9x9fZBtY to /tmp/Dire Straits - Sultans Of Swing (Alchemy Live).webm
WARNING:eyed3.mp3:Unable to find a valid mp3 frame in '/spotify/Music/Massive/Dire Straits - Sultans Of Swing.mp3'
Traceback (most recent call last):
  File "/spotify/venv/bin/spotify-playlist", line 11, in <module>
    load_entry_point('spotify-onthego==0.0.5', 'console_scripts', 'spotify-playlist')()
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/scripts/cli.py", line 42, in download_playlist
    youtube_downloader.audio(track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/youtube.py", line 45, in audio
    self.convert_or_copy(audio_file_path, track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/youtube.py", line 58, in convert_or_copy
    id3.tag(dst_path, track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/id3.py", line 9, in tag
    audiofile.tag.artist = track.artist
AttributeError: 'NoneType' object has no attribute 'artist'
```

**Comment by regisb** [comment] 2017-05-07 14:21
Well, hello again! And thanks for your thorough reporting!

Again, I can't seem to reproduce the issue, which is weird. It looks like the mp3 file that was produced from the audio file downloaded from YouTube doesn't contain any mp3 tags. Can you confirm you have `avconv` on your computer? Can you please post the output of the `avconv` command? (and the output of `ffmpeg`, while we are at it)
Also, what is your OS?

(I suspect the issue lies with `avconv`. That might be consistent with issue #22).

**Comment by Dan-Wood** [comment] 2017-05-09 04:20
```
~# avconv
avconv version 0.8.20-6:0.8.20-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Jan 19 2017 11:13:36 with gcc 4.7.2
Hyper fast Audio and Video encoder
usage: avconv [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man avconv'
```

```
# ffmpeg
ffmpeg version 0.8.20-6:0.8.20-0+deb7u1, Copyright (c) 2000-2014 the Libav developers
  built on Jan 19 2017 11:13:36 with gcc 4.7.2
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/simfs       40G  5.1G   35G  13% /
none            384M  4.0K  384M   1% /dev
none             77M  1.1M   76M   2% /run
none            5.0M     0  5.0M   0% /run/lock
none            205M     0  205M   0% /run/shm
none            100M     0  100M   0% /run/user
```

```
# locale
LANG=en_US.utf8
LANGUAGE=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
```

```
# uname -a
Linux byondpanel 2.6.32-042stab120.19 #1 SMP Mon Feb 20 20:05:53 MSK 2017 x86_64 GNU/Linu
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
```

```
# python --version
Python 2.7.3
```

Hope that helps!

**Comment by regisb** [comment] 2017-05-09 15:36
It does help! Your ffmpeg is very different than mine (on Ubuntu 16.04):

```ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609```

Your version number is lower although it's a more recent release (which is weird).

I'm going to work on making mp3 conversion compatible with your version of ffmpeg.

**Comment by Dan-Wood** [comment] 2017-05-09 22:59
Not sure how far you're into this, I'm not sure if that's the easiest thing to do in this circumstance? 

The FFMPEG I installed was from the base repo

```
# cat /etc/apt/sources.list
deb http://ftp.debian.org/debian wheezy main contrib non-free
deb http://security.debian.org wheezy/updates main contrib non-free
```

There's some nice instructions for installing on the official page
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

And this GIST

https://gist.github.com/holms/7009218

It's totally up to you if you wish to support Debian Wheezy and the default binary it's using for FFMPEG.

In the meantime I can just upgrade and see if that's the issue.

**Comment by Dan-Wood** [comment] 2017-05-09 23:15
Alright so the Multimedia repos have the updated libav-tools

```
echo "deb http://www.deb-multimedia.org wheezy main non-free" >> /etc/apt/sources.list
echo "deb-src http://www.deb-multimedia.org wheezy main non-free" >> /etc/apt/sources.list
apt-get update
apt-get install deb-multimedia-keyring # if this aborts, try again
apt-get update
apt-get install libav-tools
```
After

```
# ffmpeg
ffmpeg version 1.0.10 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jul 25 2014 07:50:40 with gcc 4.7 (Debian 4.7.2-5)
  configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --cc='ccache cc' --enable-shared --enable-libmp3lame --enable-gpl --enable-nonfree --enable-libvorbis --enable-pthreads --enable-libfaac --enable-libxvid --enable-postproc --enable-x11grab --enable-libgsm --enable-libtheora --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-libspeex --enable-nonfree --disable-stripping --enable-libvpx --enable-libschroedinger --disable-encoder=libschroedinger --enable-version3 --enable-libopenjpeg --enable-librtmp --enable-avfilter --enable-libfreetype --enable-libvo-aacenc --disable-decoder=amrnb --enable-libvo-amrwbenc --enable-libaacplus --libdir=/usr/lib/x86_64-linux-gnu --disable-vda --enable-libbluray --enable-libcdio --enable-gnutls --enable-frei0r --enable-openssl --enable-libass --enable-libopus --enable-fontconfig --enable-libfdk-aac --enable-libdc1394 --disable-altivec --dis  libavutil      51. 73.101 / 51. 73.101
  libavcodec     54. 59.100 / 54. 59.100
  libavformat    54. 29.104 / 54. 29.104
  libavdevice    54.  2.101 / 54.  2.101
  libavfilter     3. 17.100 /  3. 17.100
  libswscale      2.  1.101 /  2.  1.101
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

Now it's working.

If you could put that the above install "guide" for Wheezy up on the readme, might help other users.

**Comment by regisb** [comment] 2017-05-10 14:26
I managed to reproduce the issue. If I understand the issue correctly, it is caused by the fact that avconv cannot properly convert webm audio files, in this older version. So I think this issue should be solved by downloading audio files in m4a format instead of webm format. 

However, there is a possibility that forcing the download format to m4a will degrade the audio quality of some files (the best audio quality is not always available in m4a format). For this reason, I propose to introduce a command line option to define a preferred audio format. Could you try the following patch and tell me if it fixes your problem? https://github.com/regisb/spotify-onthego/commit/b08c1b97a2d7eb8668a55a987aa214ba7914d734

**Comment by regisb** [comment] 2017-06-15 15:24
Closing ; please reopen if the solution proposed above does not work.

**Closed by regisb** 2017-06-15 15:24 UTC
