### ISSUE TITLE
Further explanation on how to get spotify-onthego running.

### ISSUE THREAD

**Issue by MikeFrosties** [regisb/spotify-onthego#27] opened 2018-03-22 05:05 UTC
I'm relatively new to programming and all this Computer Science amazing projects that people like you are constantly developing. I'd request a more detailed explanation on how to get this project to run in my computer. In my case, I'm running Ubuntu 17. I'm assuming it comes with all the packages your project needs except for those two listed in the README file. So I have downloaded both but I have no clue what to do next. I also have my spotify app and a playlist I'd like to download.
I would appreciate if you could just be more precise with the steps one needs to follow in order to install and/or run spotify-onthego.
Thank you and thanks to the person that told me about this project, who also didn't have any idea how to run it.

**Comment by regisb** [comment] 2018-03-25 08:24
Hi @MikeFrosties, thanks for taking the time to open this issue! It's great that non-experts are interested in this package. Let's try to get you started. I am going to ask you to type specific commands in a terminal.

a) Do you know how to open a terminal?
b) Do you know your user password?

If the answer to these two questions is yes, then type the following commands in a terminal. You should type only the commands which are specially formatted, `like this`. After the first command, you will probably have to type your password because it starts with "sudo", which means "do as superuser".

1) Install the required packages: `sudo apt install -y python-pip avconv`
2) Install spotify-onthego: `sudo pip install -U spotify-onthego`
3) Download 10 of your favorite songs to your desktop: `spotify-mymusic -l 10 ~/Desktop`

Instructions 1 & 2 are only necessary the first time you install spotify-onthego, to setup your environment. After instruction 3, you will have to provide a Spotify username, client ID, client secret and redirect URI. You will also need a Google developer key for youtube. Follow the instructions provided and come back here if you have any problem.

**Comment by rgdagir** [comment] 2018-04-14 07:12
what is the redirect URI?

**Comment by regisb** [comment] 2018-04-15 13:28
@rgdagir It is confirmed that a redirect URI is no longer necessary. I'll update the documentation and the code. I'm also closing this issue: @MikeFrosties, if you still need help, feel free to comment on this (now closed) issue.

**Closed by regisb** 2018-04-15 13:28 UTC
