### ISSUE TITLE
Crashes on Single Quotes

### ISSUE THREAD

**Issue by Dan-Wood** [regisb/spotify-onthego#22] opened 2017-05-05 06:04 UTC
```
# spotify-playlist "2017" /spotify/Music/2017/
Downloading playlist '2017' (id=3otTqR4nPUywUQdLBk7zwh) from owner 'msdathk'
++ Processing KAYTRANADA - YOU'RE THE ONE
    Downloading https://www.youtube.com/watch?v=rKlA5tRu6f0 to /tmp/KAYTRANADA - YOU'RE THE ONE (feat. SYD).webm
Traceback (most recent call last):
  File "/spotify/venv/bin/spotify-playlist", line 11, in <module>
    load_entry_point('spotify-onthego==0.0.5', 'console_scripts', 'spotify-playlist')()
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/scripts/cli.py", line 42, in download_playlist
    youtube_downloader.audio(track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/youtube.py", line 45, in audio
    self.convert_or_copy(audio_file_path, track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/youtube.py", line 58, in convert_or_copy
    id3.tag(dst_path, track)
  File "/spotify/venv/local/lib/python2.7/site-packages/onthego/id3.py", line 8, in tag
    audiofile = eyed3.load(filepath)
  File "/spotify/venv/local/lib/python2.7/site-packages/eyed3/core.py", line 81, in load
    raise IOError("file not found: %s" % path)

```

**Comment by regisb** [comment] 2017-05-07 14:10
Hi, thnaks for taking the time to submit his issue!

I can't seem to reproduce this issue, as I am able to download that same song. Even though I can't reproduce, I think, the issue is *not* caused by quotes in the file name. That line of code that raises the exception should work even in the presence of quotes.

Please check : 

1. that the `/tmp/KAYTRANADA - YOU'RE THE ONE (feat. SYD).webm` file doesn't already exist,
2. the `/tmp/KAYTRANADA - YOU'RE THE ONE (feat. SYD).webm` file is writable (if it exists)
3. there is enough free space in the partition that contains the  `/tmp` folder
4. if the download succeeds after a restart.

**Comment by regisb** [comment] 2017-05-10 14:28
The root reason of this issue is the same as issue #21: an old version of avconv. Let's move all the conversation there. (closing)

**Closed by regisb** 2017-05-10 14:28 UTC
